spring:
  application:
    name: doc_service
  datasource:
    url: ${POSTGRES_JDBC_URL:jdbc:postgresql://localhost:5440/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    topic:
      document-updates: document-updates